config/routes.rb
Rails.application.routes.draw do

  resources :authors, :genres

  resources :books do 
    member do 
      resource :reviews 
    end
  end

  devise_for :users

  get "/@:username", to: "users#show", as: :user
  post "/@:username/follow", to: "users#follow", as: :follow_user
  delete "/@:username/unfollow", to: "users#unfollow", as: :unfollow_user

  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre

  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_many :authored_books 
  has_many :authors, through: :authored_books

  validates :title, :synopsis, presence: true 
  validates :authored_books, presence: true

  accepts_nested_attributes_for :authored_books, allow_destroy: true 
  
  def to_s 
    title
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.authored_books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(
        :title, :synopsis, :genre_id, 
        authored_books_attributes: [:id, :author_id, :_destroy]
      )
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for book do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :genre_id, collection: Genre.all %>
  </div>

  <div class="field">
    <%= form.input :title %>
  </div>

  <div class="field">
    <%= form.input :synopsis %>
  </div>

  <div class="field">
    <%= form.simple_fields_for :authored_books, book.authored_books do |authored_books_form| %>
      <%= authored_books_form.association :author, as: :select %>
      <%= authored_books_form.input :_destroy, as: :boolean %>
      <%= %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Synopsis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.synopsis %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @book.genre %></strong>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @book.synopsis %>
</p>

<p>
  <strong>Authors:</strong>
  <% @book.authors.each do |author| %>
    <strong><%= link_to author, author_path(author) %><strong> 
  <% end %>
</p>

<p>
  <strong>Reviews:</strong>
  <%= render @book.reviews %>
</p>

<%= link_to "New Review", new_reviews_path(@book) %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>